addr: ":8080"
cert_file:
key_file:
logger:
  level: debug
trusted_proxy: false
service_endpoints:
- http://ot.example.com/ac
dgraph:
  insecure: true
  grpc_endpoint: dgraph-grpc.teambition.test:80
open_trust:
  otid: "otid:ot.example.com:svc:ot.ac"
  domain_public_keys:
  - '{"kty":"EC","alg":"ES512","crv":"P-521","kid":"ySQYnCsV4cOZBxbHCv4E410k0gjTbi8WfJJwVkV6QqI","x":"AdtXGowadABABWC0FVolCYnRhiBEYdO6-bpyldNh1RrLVIDJJRJelA_O2UB9DyssCN8gLfJio3OdV8YH6uyfvOwb","y":"AX1Waed_878v_Y1JE2U3dLvAOIScuu_UVGUFZpQyB-hRTXMIQHTqEQw9os_Jcb491-0ZUANJZs_gne7srQ2yOCN6"}'
  private_keys:
  - '{"kty":"EC","alg":"ES256","crv":"P-256","d":"HBzwGztaoJ2DMonHyzYLZqu3q05FP68PFNdlgcLlP3o","kid":"oCr8wHUGrsMKBWeBT1wNXkZ1ixpgfP4MyPjjJaqaPoY","x":"K2VB2wMkmvRgsa4Y9G82D7BTgZf7VaA2vx5CMgRd3Xw","y":"d8zYx16ZGbXyia4p2zpQ_XJovKEQkP8k5KSJhA8k3pc"}'
